# Site Settings
title: Merry-Go-Round
email: lilliw2@gmail.com
description: >
  A Jekyll landing page with a carousel.
baseurl: "/merrygoround"
url: "http://lillworkspace.github.io"
twitter_username: 
github_username:  lillworkspace
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM